export const sexualOrientations = [
  { name: "Straight" },
  { name: "Bisexual" },
  { name: "Gay" },
  { name: "Lesbian" },
  { name: "Allosexual" },
  { name: "Androsexual" },
  { name: "Asexual" },
  { name: "Autosexual" },
  { name: "Bi-curious" },
  { name: "Closeted" },
  { name: "Demisexual" },
  { name: "Fluid" },
  { name: "Graysexual" },
  { name: "Gynesexual" },
  { name: "Heteroflexible" },
  { name: "Homosexual" },
  { name: "Pansexual" },
  { name: "Queer" },
  { name: "Questioning" },
  { name: "Sapiosexual" },
  { name: "Sex-repulsed" },
  { name: "Skoliosexual" },
  { name: "Spectrasexual" },
];
